---
title: "თვისებრივი კონტენტანალიზი(ფილიპ მაირინგი)"
description: |
  წარმოდგენილი სტატია აღწერს ტექსტის სისტემურ, ინსტრუქციებზე დაფუძნებულ ანალიზს,  რომელიც ცდილობს შეინარჩუნოს რაოდენობრივი კონტენტანალიზის მეთოდოლოგიური ძლიერი მხარეები და გაავრცელოს ისინი თვისებრივი მონაცემთა ანალიზის პროცედურებზე.
author:
  - name: თემურ გუგუშვილი 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
  - name: თამუნა ჩხაიძე 
    url: https://example.com/norajones
    affiliation: Spacely Sprockets
    affiliation_url: https://example.com/spacelysprokets
date: 06-21-2022
output:
  distill::distill_article:
    self_contained: false
    toc: true
    toc_depth: 2
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

# Learn more about creating blogs with Distill at:
# https://rstudio.github.io/distill/blog.html

```


## აბსტრაქტი

წარმოდგენილი სტატია აღწერს ტექსტის სისტემურ, ინსტრუქციებზე დაფუძნებულ ანალიზს,  რომელიც ცდილობს შეინარჩუნოს რაოდენობრივი კონტენტანალიზის მეთოდოლოგიური ძლიერი მხარეები და გაავრცელოს ისინი თვისებრივი მონაცემთა ანალიზის პროცედურებზე.

სტატიაში პირველ რიგში აღწერილია კონტენტანალიზის განვითარების ისტორია და ახსნილია ანალიზის ძირითადი პრინციპები (ანალიზის ერთეული, ეტაპებიანი მოდელები (step models), კატეგორიებთან მუშაობა, სანდოობა და ვალიდობა). შემდეგ, ნაჩვენებია კონტენტანალიზი ცენტრალური პროცედურები, კატეგორიების ინდუქციური შექმნა, კატეგორიების დედუქციური გამოყენება. სტატიაში, ასევე წარმოდგენილია აღნიშნული ანალიზის ეტაპების განხორციელების მხარდამჭერი კომპიუტერული პროგრამები. და ბოლოს, განხილულია მიდგომის შეზღუდვები და შესაძლებლობები.


## 1. შესავალი

თვისებრივი კონტენტანალიზი (MAYRING, 1983; 7th edition 2000), როგორც ამ სტატიაშია წარმოდგენილი, ტექსტის სისტემური ანალიზის მრავალ ტექნიკას მოიცავს. ანალიზის ეს მეთოდი 20 წლის წინ ლონგიტიდური კვლევის [longitudinal study] ფარგლებში შეიქმნა, რომელიც უმუშევრობის ფსიქო-სოციალურ შედეგებს აღწერდა (ULICH, HAUSSER, MAYRING et al. 1985). აღნიშნული პროექტის ფარგლებში ჩავატარეთ 600-მდე ღია ინტერვიუ, დაგვიგროვდა 20 000-ზე მეტი გვერდი ტრანსკრიპტი, რომელიც თვისებრივი მიდგომით უნდა გაანალიზებულიყო.

წარმოდგენილი ანალიზის პროცედურების ძირითადი იდეაა კომუნიკაციის შესახებ მეცნიერების ფარგლებში განვითარებული რაოდენობრივი კონტენტანალიზის უპირატესობების შენარჩუნება და მათი გავრცელება თვისებრივ-ინტერპრეტაციული ანალიზის ეტაპებზეც.

დამატებითი ინფორმაცია რაოდენობრივი კონტენტანალიზის შესახებ ხელმისაწვდომია ონლაინ [ორიგინალ ტექსტში მითითებული ბმულები არ მუშაობს]. 

(თვისებრივი) კონტენტანალიზის ობიექტი შეიძლება იყოს ნებისმიერი ტიპის ჩაწერილი კომუნიკაცია (ინტერვიუს ტრანსკრიპტი, დისკურსები, დაკვირვების პროტოკოლი, ვიდეო ჩანაწერი, დოკუმენტები ...). კონტენტანალიზი არ აანალიზებს მხოლოდ მასალის ღია/გამოხატულ შინაარს - როგორც ამას მისი სახელი მიანიშნებს. ბეკერმა და ლისმანმა (1973) განასხვავეს შინაარსის ორი დონე: 1) ტექსტის თემა და ძირითადი იდეა, როგორც  ღია შინაარსი და 2) კონტექსტი, როგორც ფარული შინაარსი. გარდა ამისა, კონტენტანალიზის მიზანს წარმოადგენს მასალის ფორმალური ასპექტების ანალიზიც. როგორც ქვემოთაა აღწერილი, კონტენტანალიზი ტექსტს ათავსებს კომუნიკაციის მოდელში, რომლის ფარგლებშიც განსაზღვრავს ანალიზის მიზანს. ამ აზრს იზიარებს კრიპენდორფიც, რომელიც კონტენტანალიზს შემდეგნაირად განმარტავს: „კონტენტანალიზი იყენებს სანდო და ვალიდურ მეთოდს ტექსტიდან მისი წყაროს სხვა მდგომარეობებსა თუ მახასიათებლებზე სპეციფიკური დასკვნების გამოსატანად“ (KRIPPENDORFF 1969, გვ. 103).

თვისებრივი კონტენტ-ანალიზი აღნიშნული ჩარჩოს ფარგლებში განისაზღვრება, როგორც ემპირიული მიდგომა, მეთოდოლოგიით მართული ტექსტის ანალიზი კომუნიკაციის კონტექსტში,  რომელიც მიყვება კონტენტანალიზის ანალიტიკურ წესებს და ეტაპებიან მოდელს ნაჩქარევი გარაოდენობრივების გარეშე.


## 2. კონტენტანალიზის ისტორია
ჩვენ შეიძლება კონტენტანალიზის განვითარების ისტორიაში განსხვავებული ფაზები გამოვყოთ  (cf. MERTEN 1983; KRIPPENDORFF 1980; MAYRING 1994a):

- **წინამორბედები:** ჰერმენევტიკულ კონტექსტში (მაგ. ბიბლიის ინტერპრეტაცია) ტექსტის ანალიზისა და შედარების განსხვავებული მიდგომები არსებობს: დაწყებული გაზეთების ადრეული ანალიზიდან, გრაფოლოგიის^[თეორია, რომლის მიხედვითაც შესაძლებელია ადამიანის ხელნაწერის საშუალებით მისი ხასიათის დადგენა. (წყარო: ხელის შესწავლა ადამიანის ხასიათის დასადგენად. უნივერსალური ენციკლოპედიური ლექსიკონი : [3 ტომად] / შეადგინა ალექსანდრე ელერდაშვილმა. - I-ლი გამოც.. - [თბ.] : ფანტაზია, 2006. - 28სმ. [MFN: 136149])] პროცედურებისა თუ ზიგმუნდ ფროიდის სიზმრის ანალიზით დამთავრებული.
- **კომუნიკაციის თეორიული საფუძველი:** მეოცე საუკუნის 20-30-იან წლებში ამერიკის შეერთებულ შტატებში, პაულ ფ. ლაზარსფელდმა და ჰაროლდ დ. ლასველმა საფუძველი ჩაუყარეს რაოდენობრივი კონტენტანალიზის  შექმნას. ამავე საუკუნის 50-იან წლებში ამ მეთოდის შესახებ პირველი სახელმძღვანელო „კონტენტანალიზი კომუნიკაციის კვლევებში“[Content Analysis in Communication Research] გამოქვეყნდა ბერნარ ბერელსონის მიერ (Berelson 1952).


